### ISSUE TITLE
Crash when tapping "Your identity key"

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#294]
SMSSecure master@38a4dee  : when I tap "Your identity key" in the menu, SMSSecure force closes. The menu item has been removed in Signal, perhaps something has slipped through the upstream patches? Logcat output:
```
12-21 22:39:42.923 E/AndroidRuntime(26687): FATAL EXCEPTION: main
12-21 22:39:42.923 E/AndroidRuntime(26687): Process: org.smssecure.smssecure, PID: 26687
12-21 22:39:42.923 E/AndroidRuntime(26687): android.content.res.Resources$NotFoundException: String resource ID #0x7f0800d6
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.content.res.Resources.getText(Resources.java:252)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.content.res.XResources.getText(XResources.java:696)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.content.res.Resources.getString(Resources.java:338)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.content.Context.getString(Context.java:350)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at org.smssecure.smssecure.ViewIdentityActivity.getDisplayString(ViewIdentityActivity.java:84)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at org.smssecure.smssecure.KeyScanningActivity.onPrepareOptionsMenu(KeyScanningActivity.java:69)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at org.smssecure.smssecure.ViewLocalIdentityActivity.onPrepareOptionsMenu(ViewLocalIdentityActivity.java:48)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.app.Activity.onPreparePanel(Activity.java:2556)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.support.v4.app.FragmentActivity.onPrepareOptionsPanel(FragmentActivity.java:487)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.support.v4.app.FragmentActivity.onPreparePanel(FragmentActivity.java:476)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.support.v7.internal.view.WindowCallbackWrapper.onPreparePanel(WindowCallbackWrapper.java:89)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onPreparePanel(AppCompatDelegateImplBase.java:296)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.support.v7.app.AppCompatDelegateImplV7.preparePanel(AppCompatDelegateImplV7.java:1144)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.support.v7.app.AppCompatDelegateImplV7.doInvalidatePanelMenu(AppCompatDelegateImplV7.java:1399)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.support.v7.app.AppCompatDelegateImplV7.access$100(AppCompatDelegateImplV7.java:89)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.support.v7.app.AppCompatDelegateImplV7$1.run(AppCompatDelegateImplV7.java:126)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.os.Handler.handleCallback(Handler.java:733)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.os.Handler.dispatchMessage(Handler.java:95)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.os.Looper.loop(Looper.java:212)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at android.app.ActivityThread.main(ActivityThread.java:5135)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at java.lang.reflect.Method.invoke(Method.java:515)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:877)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
12-21 22:39:42.923 E/AndroidRuntime(26687): 	at dalvik.system.NativeStart.main(Native Method)
12-21 22:39:42.933 D/ActivityManager(1383): New dropbox entry: org.smssecure.smssecure, data_app_crash, 5415cfae-a913-42fc-bdb6-687004df4f3a
12-21 22:39:42.933 W/ActivityManager(1383):   Force finishing activity org.smssecure.smssecure/.ViewLocalIdentityActivity
12-21 22:39:42.943 W/ActivityManager(1383):   Force finishing activity org.smssecure.smssecure/.RoutingActivity

```

**Comment by BastienLQ** [comment]
I cannot reproduce your crash. Seems related to a missing string, weird...

**Comment by johanw666** [comment]
Hmm, odd. It seems to crash in ViewLocalIdentityActivity.java, when I put a Toast in ConversationListActivity.java

```java
  private void handleMyIdentity() {
    Toast.makeText(getApplicationContext(), "handleMyIdentity entered", Toast.LENGTH_LONG).show();
    startActivity(new Intent(this, ViewLocalIdentityActivity.class));
  }
```
I see it popping up, and crash immediately after that. Still working on it with my limited Android experience because I'd hate to see the menu item go.

**Comment by johanw666** [comment]
OK, I solved it. The base class from ViewLocalIdentityActivity, ViewIdentityActivity, had a missing string: method
```java
  @Override
  protected String getScanString() {
    return getString(R.string.ViewIdentityActivity_scan_to_compare);
  }
```
uses ViewIdentityActivity_scan_to_compare, but it is nowhere defined (now I don't understand how the build succeeded at all but that's another issue).

Adding
```xml
<string name="ViewIdentityActivity_scan_to_compare">Scan to compare</string>
```
to strings.xml solved the crash. So you can revert 3299ae6 and add the string constant.

**Comment by BastienLQ** [comment]
What is the Android version of your phone?

**Comment by johanw666** [comment]
I use a Sony XPeria Z1 Compact on stock Android 4.4.4.

**Comment by BastienLQ** [comment]
OK, I got it. This string is missing in `values/strings.xml` but not in `values-*/strings.xml`, so SMSSecure crashes only using the English language. I'll open a PR.

**Comment by johanw666** [comment]
@BastienLQ wrote a script to find them: https://github.com/SilenceIM/Silence/pull/295/commits/31d822143eeeddd7bbc99892b97d7de0708143d6 I don't know if this works in your build environment.
