### ISSUE TITLE
Since 0.13 - Can't send/receive MMS secure/unsecure

### ISSUE THREAD

**Issue by benjiprod** [SMSSecure/SMSSecure#296]
Since version 0.13, I can't send/receive MMS secure/unsecure.

Phone : Nexus 5X
Operator : Orange (France)

**Comment by BastienLQ** [comment]
I need a debug log when you send/receive MMS.

**Comment by benjiprod** [comment]
https://gist.github.com/anonymous/1abb9c94d119fa3ef6cb

Since 16:11 (04:11 pm) : Started sending MMS Secure

**Comment by benjiprod** [comment]
12-24 16:11:15.667 10343 10363 W PduComposer: Making send request...
12-24 16:11:15.668 10343 10363 W PduComposer: Making message body...
12-24 16:11:15.669 10343 10363 W PduComposer: Returning: 76548 bytes...
12-24 16:11:15.669 10343 10363 W CompatMmsConnection: Sending via Lollipop API
12-24 16:11:15.671 10343 10363 W MmsBodyProvider: openFile(content://org.smssecure.provider.smssecure.mms/mms/1450969875671, w)
12-24 16:11:15.671 10343 10363 W MmsBodyProvider: Fetching message body for a single row...
12-24 16:11:15.672 10343 10363 W MmsBodyProvider: returning file /data/user/0/org.smssecure.smssecure/cache/1450969875671.mmsbody
12-24 16:11:15.702 10343 11206 W MmsBodyProvider: openFile(content://org.smssecure.provider.smssecure.mms/mms/1450969875671, r)
12-24 16:11:15.702 10343 11206 W MmsBodyProvider: Fetching message body for a single row...
12-24 16:11:15.702 10343 11206 W MmsBodyProvider: returning file /data/user/0/org.smssecure.smssecure/cache/1450969875671.mmsbody
12-24 16:12:15.840 10343 10363 W MmsSendJob: org.smssecure.smssecure.transport.UndeliverableMessageException: java.util.concurrent.TimeoutException: timeout when waiting for MMS
12-24 16:12:15.840 10343 10363 W MmsSendJob: 	at org.smssecure.smssecure.mms.OutgoingLollipopMmsConnection.send(OutgoingLollipopMmsConnection.java:85)
12-24 16:12:15.840 10343 10363 W MmsSendJob: 	at org.smssecure.smssecure.mms.CompatMmsConnection.send(CompatMmsConnection.java:34)
12-24 16:12:15.840 10343 10363 W MmsSendJob: 	at org.smssecure.smssecure.jobs.MmsSendJob.onSend(MmsSendJob.java:98)
12-24 16:12:15.840 10343 10363 W MmsSendJob: 	at org.smssecure.smssecure.jobs.SendJob.onRun(SendJob.java:37)
12-24 16:12:15.840 10343 10363 W MmsSendJob: 	at org.smssecure.smssecure.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
12-24 16:12:15.840 10343 10363 W MmsSendJob: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
12-24 16:12:15.840 10343 10363 W MmsSendJob: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
12-24 16:12:15.840 10343 10363 W MmsSendJob: Caused by: java.util.concurrent.TimeoutException: timeout when waiting for MMS
12-24 16:12:15.840 10343 10363 W MmsSendJob: 	at org.smssecure.smssecure.mms.LollipopMmsConnection.waitForResult(LollipopMmsConnection.java:74)
12-24 16:12:15.840 10343 10363 W MmsSendJob: 	at org.smssecure.smssecure.mms.OutgoingLollipopMmsConnection.send(OutgoingLollipopMmsConnection.java:74)
12-24 16:12:15.840 10343 10363 W MmsSendJob: 	... 6 more

**Comment by benjiprod** [comment]
Update : Just on secure conversation

**Comment by BastienLQ** [comment]
Hum... I can reproduce this issue in 0.12.3 and 0.13.0 on a phone with Orange France too. As it worked before in 0.12.3, I suspect a change in operator.

**Comment by benjiprod** [comment]
If I check in Chats and media option, 'Roamong auto-retrieve', there is no problem for sending MMS and **sometimes** receiving secure MMS.
