### ISSUE TITLE
Crashes on loading with large amounts of messages (90,000+)

### ISSUE THREAD

**Issue by elijahaquino** [SMSSecure/SMSSecure#297]
The app just crashes when I open it. I am using Xiaomi Mi3 on 5.1.1

**Comment by BastienLQ** [comment]
We need a debug log.

**Comment by pR0Ps** [comment]
To submit a debug log:

 - Normally (if you can open the app): Settings -> Advanced -> Send debug log, paste link here
 - From another app: Use CatLog ([Google Play](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat), [F-Droid](https://f-droid.org/repository/browse/?fdid=com.nolanlawson.logcat)), redact any sensitive information, paste log here.
 - From a computer: Install [ADB](http://developer.android.com/tools/help/adb.html) on the computer, connect the phone, run `adb logcat`, redact any sensitive information, paste log here.

**Comment by elijahaquino** [comment]
I sent log reports whenever the app crashed. For now I used the old 0.12.3
apk because the sms is really important.

**Comment by pR0Ps** [comment]
Looks like this:
```
android.database.CursorWindowAllocationException: Cursor window allocation of 2048 kb failed. # Open Cursors=741 (# cursors opened by this proc=741)
	at android.database.CursorWindow.<init>(CursorWindow.java:108)
	at android.database.AbstractWindowedCursor.clearOrCreateWindow(AbstractWindowedCursor.java:198)
	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:139)
	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
	at android.database.AbstractCursor.moveToPosition(AbstractCursor.java:197)
	at android.database.AbstractCursor.moveToNext(AbstractCursor.java:245)
	at org.smssecure.smssecure.database.DatabaseFactory$DatabaseHelper.onUpgrade(DatabaseFactory.java:780)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:256)
	at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
	at org.smssecure.smssecure.database.RecipientPreferenceDatabase.getRecipientsPreferences(RecipientPreferenceDatabase.java:80)
	at org.smssecure.smssecure.recipients.RecipientProvider.getIndividualRecipientDetails(RecipientProvider.java:133)
	at org.smssecure.smssecure.recipients.RecipientProvider.getRecipientDetailsSync(RecipientProvider.java:129)
	at org.smssecure.smssecure.recipients.RecipientProvider.getRecipient(RecipientProvider.java:82)
	at org.smssecure.smssecure.recipients.RecipientProvider.getRecipients(RecipientProvider.java:96)
	at org.smssecure.smssecure.recipients.RecipientFactory.getRecipientsForIds(RecipientFactory.java:106)
	at org.smssecure.smssecure.recipients.RecipientFactory.getRecipientsFromString(RecipientFactory.java:81)
	at org.smssecure.smssecure.jobs.SmsReceiveJob.isBlocked(SmsReceiveJob.java:70)
	at org.smssecure.smssecure.jobs.SmsReceiveJob.onRun(SmsReceiveJob.java:50)
	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

**Comment by johanw666** [comment]
Signal shows only the first 500 messages in a conversation by defaut, it shows the rest if you select it. I can't find that commit anywhere backported to SMSSecure, it might sole this issue.,

**Comment by BastienLQ** [comment]
@johanw666 We do this, too.

**Comment by tuxayo** [comment]
I'm still holding on 0.12.3 because of that issue, it there something I can do to help?

**Comment by BastienLQ** [comment]
@tuxayo You could try to reproduce the bug. I have ~3000 message without experiencing this issue, so debugging is hard.

**Comment by BastienLQ** [comment]
I can upgrade from 0.12.3 to 0.13.1 with 121 680 messages in database...

**Comment by tuxayo** [comment]
@BastienLQ 
> You could try to reproduce the bug. I have ~3000 message without experiencing this issue, so debugging is hard.

I there any database structure change (from 0.12.3) that could prevent downgrading after a eventual failed upgrade to the latest version?

**Comment by BastienLQ** [comment]
@tuxayo Yes, the database version is checked.

**Comment by tuxayo** [comment]
I could upgrade without issues, thanks! (oandbackup was used to save app data)
