### ISSUE TITLE
NPE in MessageNotifier

### ISSUE THREAD

**Issue by pR0Ps** [SMSSecure/SMSSecure#324]
From the dev console:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.Ringtone.setAudioAttributes(android.media.AudioAttributes)' on a null object reference
	at org.smssecure.smssecure.notifications.MessageNotifier.sendInThreadNotification(MessageNotifier.java:282)
	at org.smssecure.smssecure.notifications.MessageNotifier.notifyMessageDeliveryFailed(MessageNotifier.java:101)
	at org.smssecure.smssecure.jobs.MmsSendJob.notifyMediaMessageDeliveryFailed(MmsSendJob.java:258)
	at org.smssecure.smssecure.jobs.MmsSendJob.onSend(MmsSendJob.java:110)
	at org.smssecure.smssecure.jobs.SendJob.onRun(SendJob.java:37)
	at org.smssecure.smssecure.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

Slightly different:
```
java.lang.NullPointerException
	at org.smssecure.smssecure.notifications.MessageNotifier.sendInThreadNotification(MessageNotifier.java:286)
	at org.smssecure.smssecure.notifications.MessageNotifier.updateNotification(MessageNotifier.java:140)
	at org.smssecure.smssecure.jobs.MmsDownloadJob.storeRetrievedMms(MmsDownloadJob.java:231)
	at org.smssecure.smssecure.jobs.MmsDownloadJob.onRun(MmsDownloadJob.java:126)
	at org.smssecure.smssecure.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
```

**Comment by HubGit2016** [comment]
I'm using SMSSecure on LG Spirit and I have some problems with notifications. Sometimes I see them only when I open the app, and sometimes never.

**Comment by HubGit2016** [comment]
https://gist.github.com/anonymous/cd061d30e6ab5e9c143f935897d029b0 This is my debug log generated after receiving a delayed notification which I saw after opening the app.
