### ISSUE TITLE
Crash after update from 0.5.3 - 0.5.4

### ISSUE THREAD

**Issue by johanw666** [SMSSecure/SMSSecure#92]
Sorry to spoil it again, but after I built 0.5.4 and upgraded SMSSecure crashed after I entered my password. Fortunately, this time re-installing 0.5.3 fixed the issue and I did not need to recover my database with Titanium Backup.

AppDowngrader (http://forum.xda-developers.com/android/apps-games/root-appdowner-downgrade-apps-easy-t2828705) is a real help these days. Requires root but can install an older version over a newer one.

Anyway, the logfile:

```
04-09 00:23:56.300 E/AndroidRuntime(19707): FATAL EXCEPTION: main
04-09 00:23:56.300 E/AndroidRuntime(19707): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.smssecure.smssecure/org.smssecure.smssecure.DatabaseUpgradeActivity}: java.lang.NullPointerException
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2343)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.ActivityThread.access$600(ActivityThread.java:162)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.os.Handler.dispatchMessage(Handler.java:107)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.os.Looper.loop(Looper.java:194)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.ActivityThread.main(ActivityThread.java:5371)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at java.lang.reflect.Method.invokeNative(Native Method)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at java.lang.reflect.Method.invoke(Method.java:525)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at dalvik.system.NativeStart.main(Native Method)
04-09 00:23:56.300 E/AndroidRuntime(19707): Caused by: java.lang.NullPointerException
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1416)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.Activity.startActivityForResult(Activity.java:3388)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.Activity.startActivityForResult(Native Method)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.Activity.startActivityForResult(Activity.java:3349)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.Activity.startActivityForResult(Native Method)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:817)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.Activity.startActivity(Activity.java:3584)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.Activity.startActivity(Native Method)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.Activity.startActivity(Activity.java:3552)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:631)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.Activity.startActivity(Native Method)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at org.smssecure.smssecure.DatabaseUpgradeActivity.onCreate(DatabaseUpgradeActivity.java:90)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.Activity.performCreate(Activity.java:5122)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1081)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2307)
04-09 00:23:56.300 E/AndroidRuntime(19707): 	... 12 more
04-09 00:23:56.394 E/AppErrorDialog(487): Failed to get ILowStorageHandle instance
04-09 00:23:57.379 D/libc-netbsd(130): res_queryN name = ecget.7176.com succeed
04-09 00:23:57.379 D/libc-netbsd(19684): getaddrinfo: ecget.7176.com get result from proxy >>
04-09 00:23:58.240 E/InputDispatcher(487): channel '41bf2098 org.smssecure.smssecure/org.smssecure.smssecure.PassphrasePromptActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
```

**Comment by pR0Ps** [comment]
Fortunately, we can still correct this before the update goes out. I haven't been able to reproduce this but it looks like something similar to what @BastienLQ [fixed previously](https://github.com/SMSSecure/SMSSecure/commit/9b1e275d3d11a50716e5724949be7191a45bdd14).

Would you be able to join our IRC channel? (https://webchat.freenode.net/?channels=SMSSecure) to test this with me?

**Comment by pR0Ps** [comment]
Thanks for catching this. I've committed the fix and incorporated it into the v0.5.4 release.

**Comment by johanw666** [comment]
OK, this new version runs OK. It doesn't even update the database when I start it on neither of my devices, the one with the crash yesterday and the other one where I didn't install a 0.5.4 on before.

**Comment by johanw666** [comment]
On 09-04-2015 1:00, Carey Metcalfe wrote:

> Would you be able to join our IRC channel?
> (https://webchat.freenode.net/?channels=SMSSecure) to test this with me?

I just saw this after I went to bed. Timezones...

Unfortunately not, the IRC server blocks me because I run a Tor exit
node. The one day I used it I was somewhere else.

Anyway, you can reach me on johanw@xs4all.nl.

-- 
With kind regards,

Johan Wevers
